### PR TITLE
Update publications.md

### PR DESCRIPTION
**Pull request by LukasRoeseler**
Corrected DOI for Altmetrics Donut - can somebody please check whether this is correct? I ahve no experience with altmetrics and simply copied the format from other entries, sorry!

### CODE REVIEW

**Comment by flavioazevedo** [comment]
It seems that the Donut is not picking up impact on the preprint.

image 

It got shared a lot on social media, right? 

Is this the link we are using? https://doi.org/10.31222/osf.io/me2ub

I am not sure why. Let's try this and hope it works!

**Comment by LukasWallrich** [comment]
@flavioazevedo remember that you can check changes on staging.forrt.org (for the PR that was edited most recently, or the one you manually staged there). In this case, the new donut still does not work, so there is little point in merging this.

**Comment by LukasWallrich** [comment]
The issue is not about our setup - for some reason, altmetric does not have data on the preprint:

image

(The same works to see the data for our other preprints.) If someone wants to report that to them and troubleshoot further, please go ahead ... but I would close this PR.

**Comment by flavioazevedo** [comment]
Done. Sent the email. Please reply to them if I forgot anything.

**Pull request merged**
