### PR TITLE
Update menus.toml

### PR DESCRIPTION
**Pull request by LukasRoeseler**
Added FReD R-Package to Replication Hub menu, closes #55

### CODE REVIEW

**Comment by flavioazevedo** [comment]
Hi @LukasWallrich , I tried to figure out what Luke is trying to do via the code but couldn't (clearly my issue). For some reason, it is not on https://staging.forrt.org/ (at least I couldn't find a page called "FReD R-Package". Would you mind checking this please?

**Comment by LukasWallrich** [comment]
We can always only the the PR that was added or changed most recently on staging - so this was disappeared again. We could show it again by running the action manually, selecting this branch, or making an edit.

**Comment by LukasWallrich** [comment]
Luke only added a link to the R package to the menu, so I don't think it can break anything - therefore I will take the risk to approve it without re-staging in this case.

**Review by LukasWallrich — APPROVED** [review]

**Comment by LukasWallrich** [comment]
> Added FReD R-Package to Replication Hub menu, closes #55

@LukasRoeseler just to note, issue number are repository-specific, so this links to the wrong 55. Not important for the change, but wanted to let you know.

**Comment by flavioazevedo** [comment]
Hi @LukasWallrich , thanks for the explanation. It makes sense that the staging env only works for the latest change. Thanks for explaining the basic, too. It often is what is missing. 

In any case, would it be possible for the shiny apps and the R-package open on a new tab, please? this is so folks are still insider of FORRT website and hopefully generate browsing.

**Comment by LukasWallrich** [comment]
Good idea, though we'll need to check that it does not trigger popup blockers. Can you add an issue? Otherwise I'll try to remember it :)

**Pull request merged**
