### PR TITLE
Neurodiversify your Curriculum Talk 

### PR DESCRIPTION
**Pull request by richarddushime**
I added the Neurodiverisfy your curriculum Unconference   talk by [Magdalena Grose-Hodge](https://osf.io/wrux8) and [Lorna Hamilton](https://osf.io/ewmrq)  
@SamGuay and @flavioazevedo 
Requesting for your review 
Thanks

### CODE REVIEW

**Review by flavioazevedo — APPROVED** [review]
This looks great! Thank you Richard!

**Comment by richarddushime** [comment]
> Hm, the Github checks says it is failing. Let me tag @SamGuay here to see if he can identify why that is happening.
> 
> image

thats what i am asking myself 
what is blocking ?

**Comment by SamGuay** [comment]
The is a fake error, checks will pass once it is merged!

**Comment by SamGuay** [comment]
Could a PDF of the talk be added as well so people can download either the .PPTX or .PDF. Ideally with a name without space :)

**Comment by richarddushime** [comment]
> Could a PDF of the talk be added as well so people can download either the .PPTX or .PDF. Ideally with a name without space :)

the pdf can be downloaded via the [osf home ](https://osf.io/download/yu6ch/)

**Review by flavioazevedo — COMMENTED** [review]
I will approve this even if the checks fail because @SamGuay says it is a 'fake' fail. Fingers crossed!

**Review by flavioazevedo — COMMENTED** [review]
I will approve this even if the checks fail because @SamGuay says it is a 'fake' fail. Fingers crossed!

**Comment by flavioazevedo** [comment]
@SamGuay , it doesn't let me approve it??

**Pull request merged**
