### PR TITLE
Restore Thomas

### PR DESCRIPTION
**Pull request by LukasWallrich**
@flavioazevedo if you approve and merge this, Thomas should be back :)

### CODE REVIEW

**Comment by richarddushime** [comment]
> @flavioazevedo if you approve and merge this, Thomas should be back :)

I was just from checking both staging and forrt.org 
and I did not see Thomas's page 

Thanks for fixing this

**Comment by richarddushime** [comment]
@LukasWallrich Thanks for this 
I just made a commit to update the featured image

**Comment by richarddushime** [comment]
@flavioazevedo Good  to go :rocket:

**Comment by LukasWallrich** [comment]
Thanks everyone! 

@flavioazevedo, to clarify, staging always only shows the PR that was edited last - you can go to Actions -> deploy and then select to run it on a specific branch if you want to see an earlier PR in staging again.

**Comment by flavioazevedo** [comment]
OK, I learned about this now. Go to the tab Actions, find the PR, run all actions on that specific PR :) Thank you!

**Pull request merged**
