### PR TITLE
Updating Google Tag Manager script

### PR DESCRIPTION
**Pull request by bethaniley**
This is to update the Google Tag Manager script. This is part of the process to convert from Google Universal Analytics to Google Analytics 4. Created using the setup tool, as per the [Google analytics migration guide](https://support.google.com/analytics/answer/10759417).

This can't be tested until it's pushed to main because it needs to be embedded on the website and we don't have a testing sub-domain!

### CODE REVIEW

**Comment by DAKiersz** [comment]
Missing Google ID changes in config? @bethaniley

**Comment by bethaniley** [comment]
Nope, it's staying the same!

**Comment by DAKiersz** [comment]
GH Pages do not support staging environments in a way other cloud solutions do (Netlify, Azure, AWS etc.) which makes acceptance/perf testing tricky at present - local and CI builds are currently what we have. 

For now, approve for release.

**Comment by DAKiersz** [comment]
GH Pages do not support staging environments in a way other cloud solutions do (Netify, Azure, AWS) which makes testing it tricky, local and CI build is all we have at this minute.

**Comment by bethaniley** [comment]
I was wrong, it needed to be updated :)

**Review by DAKiersz — APPROVED** [review]

**Pull request merged**
