### PR TITLE
Rectify reminder workflow timings

### PR DESCRIPTION
**Pull request by DAKiersz**
## Changes

Running this check hourly is not necessary, and it consumes into our limited GH Action minutes. One daily check at 1am should suffice.

Actions are pinned to specific commits as per good practices.

Minor formatting/naming changes to workflows.

### CODE REVIEW

**Review by helenahartmann — APPROVED** [review]

**Comment by flavioazevedo** [comment]
Hi there @DAKiersz , I tried everything to approve this pull request, but I couldn't find a way 😬

**Comment by DAKiersz** [comment]
> Hi there @DAKiersz , I tried everything to approve this pull request, but I couldn't find a way 😬

Have you tried going to 'Files changed' below the title? There should be a green button called 'Review changes' where you can approve/comment/request changes.

This might help https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/about-pull-request-reviews#discovering-and-navigating-conversations

**Review by flavioazevedo — APPROVED** [review]

**Comment by LukasWallrich** [comment]
Good change, thanks - but for my understanding: are GH minutes actually charged for actions in public repos? I thought they aren't ...

**Comment by DAKiersz** [comment]
> Good change, thanks - but for my understanding: are GH minutes actually charged for actions in public repos? I thought they aren't ...

I looked this up actually, and it does appear that you are correct based on https://docs.github.com/en/billing/managing-billing-for-github-actions/about-billing-for-github-actions Good spot, learned something new today.

**Pull request merged**
